[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]"]

[tool.setuptools_scm]
write_to = "bread/version.py"

[tool.black]
exclude = '(migrations|\.hg|\.venv|\.eggs|\.tox|version.py)'
