# Generated by Django 3.2.6 on 2022-01-18 06:20

import bread.contrib.reports.fields.queryfield
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triggers.action')),
                ('email', models.CharField(help_text='\nSyntax:\n- Email: example@example.com\n- User/Group: @username\n- From object: manager.email (actually object.manager.email)\n\nMultiple values van be separated by comma , e.g.\nboss@example.com, @adminuser, @reviewteam, primary_email_address.email\n', max_length=255, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Send Email',
                'verbose_name_plural': 'Send Email Actions',
            },
            bases=('triggers.action',),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(help_text='\nDatabase change: added, changed, deleted\nDate or time in ISO 8601 format: YYYY-MM-DD hh:mm:ss\nDate field from object: field:reminder.date 2 weeks ago\n\nMultiple values van be separated by comma , e.g.\nchanged, YYYY-MM-DD hh:mm:ss, field:reminder.date in 2 weeks\n', verbose_name='Event')),
                ('filter', bread.contrib.reports.fields.queryfield.QuerysetField(blank=True, modelfieldname='model', verbose_name='Filter')),
                ('enable', models.BooleanField(default=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='triggers.action')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
            },
        ),
    ]
