# Generated by Django 3.2.9 on 2022-01-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_templates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttemplate",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="model",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
