# Generated by Django 3.1.5 on 2021-02-25 08:36

import django.db.models.deletion
from django.db import migrations, models

import bread.contrib.reports.fields.modelfieldlookup


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "filter",
                    bread.contrib.reports.fields.queryfield.QuerysetField(
                        "Filter", modelfieldname="model"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    bread.contrib.reports.fields.modelfieldlookup.ModelFieldLookup(
                        verbose_name="Column"
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        blank=True,
                        choices=[("count", ""), ("sum", "")],
                        max_length=64,
                        verbose_name="Aggregation",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reports.report"
                    ),
                ),
            ],
        ),
    ]
