# Generated by Django 3.1.5 on 2021-03-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['name'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='???', max_length=255),
            preserve_default=False,
        ),
    ]
