# Generated by Django 3.1.5 on 2021-03-01 05:29

import django.db.models.deletion
from django.db import migrations, models

import bread.contrib.reports.fields.modelfieldlookup


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210301_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcolumn',
            name='column',
            field=bread.contrib.reports.fields.modelfieldlookup.ModelFieldLookup(max_length=255, verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='reportcolumn',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='reports.report'),
        ),
    ]
