# Generated by Django 4.0.5 on 2022-08-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0004_datachangetrigger_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triggers.action')),
                ('message', models.TextField(help_text="Will be rendered as a Django template with the name 'object' in the context", verbose_name='Message')),
            ],
            options={
                'verbose_name': 'System notification',
                'verbose_name_plural': 'System notifications',
            },
            bases=('triggers.action',),
        ),
        migrations.AlterModelOptions(
            name='sendemail',
            options={'verbose_name': 'Send email action', 'verbose_name_plural': 'Send email actions'},
        ),
    ]
