# Generated by Django 4.1.5 on 2023-03-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_templates", "0006_fix_date_formatting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttemplatevariable",
            name="value",
            field=models.CharField(
                blank=True,
                help_text="Path to the desired value (see help)",
                max_length=255,
                verbose_name="Value",
            ),
        ),
    ]
