# Generated by Django 4.1.7 on 2023-08-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customforms", "0003_alter_pdfformfield_customform_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pdfformfield",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pdfformfield",
            name="join",
            field=models.CharField(
                blank=True,
                help_text="Join multiple fields with character, use \\n for newline",
                max_length=16,
                verbose_name="Join",
            ),
        ),
        migrations.AlterField(
            model_name="pdfformfield",
            name="customform_field",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"customform": models.F("customform")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customforms.customformfield",
            ),
        ),
    ]
