# Generated by Django 4.1.7 on 2023-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "customforms",
            "0004_alter_pdfformfield_unique_together_pdfformfield_join_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfformfield",
            name="mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map PDF-field value",
                verbose_name="Map value",
            ),
        ),
    ]
